baseURL = "http://localhost:1313/"
languageCode = "id"
title = "santaidikit"
theme = "PaperMod"

[params]
  env = "development"

[markup]
  [markup.highlight]
    style = "github-dark"
    noClasses = false