baseURL = "https://santaidikit.online/"
languageCode = "id"
title = "santaidikit"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  env = "development"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4
    wrapperClass = 'highlight'

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true