baseURL = "https://santaidikit.online/"
languageCode = "id"
title = "santaidikit"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  env = "development"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4
    wrapperClass = 'highlight'

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [outputs]
    home = ['html', 'rss']
    section = ['html', 'rss']
    taxonomy = ['html']
    term = ['html']

defaultContentLanguage = "id"
defaultContentLanguageInSubdir = true
[languages]

[languages.id]
languageName = "Bahasa Indonesia"
weight = 1
title = "santai dikit online"
languageCode = "id"

[languages.en]
languageName = "English"
weight = 2
title = "santai dikit online"
languageCode = "en"

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "no-cache"

